name       : xorg-driver-input-wacom
version    : 0.34.2
release    : 14
source     :
    - https://netcologne.dl.sourceforge.net/project/linuxwacom/xf86-input-wacom/xf86-input-wacom-0.34.2.tar.bz2 : 2ad1b9db141104370aef4966aae419dde915caea316e1df2c6ac063545706b1c
license    :
    - MIT
summary    : Input driver for Wacom/Wacom-like tablets
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xinerama)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   : no-bind-now
component  : xorg.driver
description: |
    The Xorg Wacom Driver package contains the X.Org X11 driver for Wacom and Wacom-like tablets. It is not required to use a Wacom tablet, the xf86-input-evdev driver can handle these devices without problems.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
